name: example
publish_to: none
environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  analyzer: ">=2.0.0 <6.0.0"
  build: ^2.0.0
  build_config: ^1.0.0

dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^3.0.0
