builders:
  diagnosticable_builder:
    import: "package:diagnosticable_generator/builder.dart"
    builder_factories: ["diagnosticableBuilder"]
    build_extensions: {".dart": ["diagnosticable.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]